# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: BEAST 2
email: 
description: The extensible Bayesian phylogenetic analysis platform.

#baseurl: "" # This is automatically filled in by GitHub.

url: "http://beast2.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge

# Pagination
gems: [jekyll-paginate]
paginate_path: "/blog/page:num/"
paginate: 10

collections:
    pages:
        output: true
        permalink: /:path/
    orphans:
        output: true
    features:
        output: true


#site map
#gems:
#  - jekyll-sitemap
timezone: Pacific/Auckland
